// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwtPf2rk1_OGHOxYNDZIfisIrc5uq-Mns',
    appId: '1:570073065219:web:a2a7121448a20c66bbeb36',
    messagingSenderId: '570073065219',
    projectId: 'flutterauth-f1fb0',
    authDomain: 'flutterauth-f1fb0.firebaseapp.com',
    storageBucket: 'flutterauth-f1fb0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgRw3c1xbi__bGuemB6xmU60yZqG3xvdE',
    appId: '1:570073065219:android:defed7bc94672504bbeb36',
    messagingSenderId: '570073065219',
    projectId: 'flutterauth-f1fb0',
    storageBucket: 'flutterauth-f1fb0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_REf0GbFRMViVZBnC7llSYueQbWfpA1c',
    appId: '1:570073065219:ios:8d81589fdc8251e5bbeb36',
    messagingSenderId: '570073065219',
    projectId: 'flutterauth-f1fb0',
    storageBucket: 'flutterauth-f1fb0.firebasestorage.app',
    iosBundleId: 'com.example.getStarted',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_REf0GbFRMViVZBnC7llSYueQbWfpA1c',
    appId: '1:570073065219:ios:8d81589fdc8251e5bbeb36',
    messagingSenderId: '570073065219',
    projectId: 'flutterauth-f1fb0',
    storageBucket: 'flutterauth-f1fb0.firebasestorage.app',
    iosBundleId: 'com.example.getStarted',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwtPf2rk1_OGHOxYNDZIfisIrc5uq-Mns',
    appId: '1:570073065219:web:87ca70146724f37abbeb36',
    messagingSenderId: '570073065219',
    projectId: 'flutterauth-f1fb0',
    authDomain: 'flutterauth-f1fb0.firebaseapp.com',
    storageBucket: 'flutterauth-f1fb0.firebasestorage.app',
  );
}
